spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ldl683411

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/neo/mapper/*.xml
  type-aliases-package: com.neo.model